// TODO : 

"li t1, 128\n\t"
"vsetvli t0, t1, e16, ta, ma\n\t"
"vmv.v.x v0, %[target]\n\t"
"vle16.v v1, (%[p_x])\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"lw t2, (%[p_x])\n\t"
"vmv.v.x v2, t2\n\t"
"vadd.vv v2, v1, v2\n\t"
"vmseq.vv v3, v2, v0\n\t"
"vcpop.m t2, v3\n\t"
"or %[flag], %[flag], t2\n\t"
"addi %[p_x], %[p_x], 2\n\t"

"beqz %[flag], exit\n\t"
"li %[flag], 1\n\t"

"exit:\n\t"